#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
  resource: '../src/Controller'
  type: 'annotation'

currencies-mono:
  path: /api/currencies/mono
  controller: App\Controller\CurrencyController::monoBank
  methods: GET

currencies-privat:
  path: /api/currencies/privat
  controller: App\Controller\CurrencyController::privatBank
  methods: GET
